### ISSUE TITLE
exception when running

### ISSUE THREAD

**Issue by szabgab** [TabeaHeckenthaler/MachineLearning#1]
```python index.py ```

I got an error
```
Traceback (most recent call last):
  File "/home/gabor/work/wis/TabeaHeckenthaler-MachineLearning/index.py", line 10, in <module>
    df = pd.DataFrame(pd.read_json(df_dir))
  File "/home/gabor/venv3/lib/python3.9/site-packages/pandas/util/_decorators.py", line 199, in wrapper
    return func(*args, **kwargs)
  File "/home/gabor/venv3/lib/python3.9/site-packages/pandas/util/_decorators.py", line 299, in wrapper
    return func(*args, **kwargs)
  File "/home/gabor/venv3/lib/python3.9/site-packages/pandas/io/json/_json.py", line 563, in read_json
    return json_reader.read()
  File "/home/gabor/venv3/lib/python3.9/site-packages/pandas/io/json/_json.py", line 694, in read
    obj = self._get_object_parser(self.data)
  File "/home/gabor/venv3/lib/python3.9/site-packages/pandas/io/json/_json.py", line 716, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "/home/gabor/venv3/lib/python3.9/site-packages/pandas/io/json/_json.py", line 831, in parse
    self._parse_no_numpy()
  File "/home/gabor/venv3/lib/python3.9/site-packages/pandas/io/json/_json.py", line 1079, in _parse_no_numpy
    loads(json, precise_float=self.precise_float), dtype=None
ValueError: Expected object or value
```

**Comment by TabeaHeckenthaler** [comment]
Hmm, I don't get this error. After a google search, I think, the problem might be , that the program didn't have access to the .json files. To run the program, they must be in the same folder as the index.py script. 

I hope this solves the problem.

**Comment by szabgab** [comment]
I'd suggest the code should check for this and provide a clear indication to the user.

BTW Once you have "done" an issue you can close it.

**Comment by TabeaHeckenthaler** [comment]
Thanks :) I will close this issue as soon as you let me know the code is not giving you this error.
